### ISSUE TITLE
Suhiswap masterchef subgraph is dead

### ISSUE THREAD

**Issue by NBFinanceTech** [sushiswap/sushiswap-subgraph#103]
![image](https://user-images.githubusercontent.com/66219221/192777538-05f38f67-4aa9-4708-9c2a-379c50b59ead.png)

**Comment by NBFinanceTech** [comment]
URL: https://thegraph.com/hosted-service/subgraph/sushiswap/master-chef

**Comment by jiro-ono** [comment]
@NBFinanceTech Use this one: https://thegraph.com/hosted-service/subgraph/jiro-ono/masterchef-staging

That prod one above died, and don't think we'll be pushing a fix up for it since the mainnet subgraphs are gonna be sunset within a month or so.

**Comment by NBFinanceTech** [comment]
Thx
