### ISSUE TITLE
Add Token & Pair entities to MasterChef Subgraph

### ISSUE THREAD

**Issue by jiro-ono** [sushiswap/sushiswap-subgraph#23]
+ Token & Pair entities will make it easier for displaying and searching for specific pools.

+ Token entities will consist of: id(address), symbol, and decimals.
+ Pair entities will consist of: id(address), token0 (token entity), token1 (token entity)

+ Probably will just need to add contracts calls when creating a new Pair to index the symbol, name, and address.

**Comment by matthewlilley** [comment]
Yeah, this is a good idea. The number of pools is quite limited so it'll basically be cost-free.
