### ISSUE TITLE
Bug with Token Pricing

### ISSUE THREAD

**Issue by jiro-ono** [sushiswap/sushiswap-subgraph#29]
+ An issue was raised for the exchange subgraph, where someone noticed that the pricing or `derivedETH` property on the `Token` entity is about half as much as it should be.

+ The token is `Badger` and the bug can be seen with this query:

```
{
  token (id: "0x3472a5a71965499acd81997a54bba8d852c6e53d") {
    id
    name
    symbol
    derivedETH
  }
}
```

The result of the query at the time of writing this issue is here:

```
{
  "data": {
    "token": {
      "derivedETH": "0.007107683004521135948939587780566205",
      "id": "0x3472a5a71965499acd81997a54bba8d852c6e53d",
      "name": "Badger",
      "symbol": "BADGER"
    }
  }
}
```

**Comment by matthewlilley** [comment]
Pending sync with the expected fix here:

https://thegraph.com/explorer/subgraph/matthewlilley/exchange?version=pending
