### ISSUE TITLE
Update SushiMaker for latest contract

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-subgraph#38]
Maker is still configured to use an old address, the latest version of maker is 0xE11fc0B43ab98Eb91e9836129d1ee7c3Bc95df50

**Comment by Xavier59** [comment]
Update was already done here : https://github.com/sushiswap/sushiswap-subgraph/commit/8e20ec233ce4ead6f6d2a19a86df77cec00e3cdb

Maker subgraph seems to sync correctly. Closing this
