### ISSUE TITLE
Matic chain Pairs(reserveUSD) is 0

### ISSUE THREAD

**Issue by speedmax** [sushiswap/sushiswap-subgraph#92]
https://thegraph.com/hosted-service/subgraph/sushiswap/matic-exchange

In the last 3 days, the pairs#reserveUSD property has become zero. Are there any pricing service that is broken?

```
{
  pairs(first: 5) {
    id,
    reserveUSD
  }
}
```
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/3823/164192549-36483833-cc9a-4240-a58b-5b258d8f6cfc.png">

**Comment by jiro-ono** [comment]
Yeah sorry about this, there is actually a bug from a recent deployment into the prod version of the subgraph. Working with the graph team currently on restore that old one, and getting it back into this endpoint. Will probably be a few days or longer before it's gets all fixed.

**Comment by nfeignon** [comment]
Issue seems to be fixed, thanks!

**Comment by speedmax** [comment]
Many Thanks nick, It works now and I will close it.
