### ISSUE TITLE
error There are more than one workspace with name "maker"

### ISSUE THREAD

**Issue by unicardano** [sushiswap/sushiswap-subgraph#93]

**Comment by jiro-ono** [comment]
We need to update the docs for building and deploying these subgraphs, but process I follow is:

`cd packages/constants`
`yarn prepare:mainnet`
`cd ../subgraphs/masterchef`
`yarn prepare:mainnet`
'yarn codegen`
'yarn deploy:mainnet`

**Comment by unicardano** [comment]
they made a mistake and set two workspaces namely maker!
